version: '3'
services:
  app:
    container_name: app-hero
    image: app-hero:v1
    build: .
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge