version: '3'
services:
  app:
    container_name: app-hero
    image: app-hero:v1
    build: .
    ports:
      - "8082:8082"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge